controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_group_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController


joint_group_velocity_controller:
  ros__parameters:
    joints: 
      - "joint_5"
      - "joint_4"


diff_drive_controller:
  ros__parameters:

    # left_wheel_names: ["front_left_joint","back_left_joint"]
    # right_wheel_names: ["front_right_joint","back_right_joint"]

    left_wheel_names: ["joint_3", "joint_0"]
    right_wheel_names: ["joint_1", "joint_2"]

    left_wheel_directions: [-1, 1]
    right_wheel_directions: [1, -1]

    wheel_separation: 0.5
    wheels_per_side: 2  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.2

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    position_feedback: false # continuous servos (for driving) connected to pca9685 don't have position feedback
    open_loop: true
    enable_odom_tf: false

    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    use_stamped_vel: false
    #velocity_rolling_window_size: 10

    # # Velocity and acceleration limits
    # # Whenever a min_* is unspecified, default to -max_*
    # linear.x.has_velocity_limits: true
    # linear.x.has_acceleration_limits: true
    # linear.x.has_jerk_limits: false
    # linear.x.max_velocity: 1.0
    # linear.x.min_velocity: -1.0
    # linear.x.max_acceleration: 1.0
    # linear.x.max_jerk: 0.0
    # linear.x.min_jerk: 0.0

    # angular.z.has_velocity_limits: true
    # angular.z.has_acceleration_limits: true
    # angular.z.has_jerk_limits: false
    # angular.z.max_velocity: 1.0
    # angular.z.min_velocity: -1.0
    # angular.z.max_acceleration: 1.0
    # angular.z.min_acceleration: -1.0
    # angular.z.max_jerk: 0.0
    # angular.z.min_jerk: 0.0

